steps:
  # Step 1: Build the Docker image from your source code
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/fetchbot-repo/fetchbot-api', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/fetchbot-repo/fetchbot-api']

  # Step 3: Deploy the image to Cloud Run with secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fetchbot-api'
      - '--image'
      - 'us-docker.pkg.dev/$PROJECT_ID/fetchbot-repo/fetchbot-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      # Set non-sensitive environment variables directly
      - '--set-env-vars'
      - 'FLASK_ENV=production,FLASK_DEBUG=False,RATELIMIT_DEFAULT=200 per day;50 per hour'
      # Set sensitive environment variables from secrets
      - '--set-secrets'
      - 'SECRET_KEY=SECRET_KEY:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,DATABASE_URL=DATABASE_URL:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_KEY=SUPABASE_KEY:latest,OAUTH_CLIENT_ID=OAUTH_CLIENT_ID:latest,OAUTH_CLIENT_SECRET=OAUTH_CLIENT_SECRET:latest,OAUTH_CALLBACK_URL=OAUTH_CALLBACK_URL:latest'

# Optionally list the image so it shows up in the Cloud Build UI
images:
  - 'us-docker.pkg.dev/$PROJECT_ID/fetchbot-repo/fetchbot-api'

# Configure logging options
options:
  logging: CLOUD_LOGGING_ONLY